/**
 * title: 基础
 * desc: 云标签
 */

import React, { FC } from 'react';
import { TagCloud } from 'ant-design-atom';

const data = [
  { name: '常州市', value: 91 },
  { name: '黄石市', value: 25 },
  { name: '池州市', value: 75 },
  { name: '营口市', value: 63 },
  { name: '重庆市', value: 27 },
  { name: '咸阳市', value: 87 },
  { name: '乐山市', value: 44 },
  { name: '银川市', value: 11 },
  { name: '黔西南布依族苗族自治州', value: 93 },
  { name: '海外', value: 1 },
  { name: '石嘴山市', value: 21 },
  { name: '泰安市', value: 69 },
  { name: '红河哈尼族彝族自治州', value: 78 },
  { name: '海外', value: 52 },
  { name: '泰州市', value: 16 },
  { name: '澳门半岛', value: 28 },
  { name: '漯河市', value: 15 },
  { name: '滨州市', value: 15 },
  { name: '开封市', value: 92 },
  { name: '黔西南布依族苗族自治州', value: 53 },
  { name: '长治市', value: 55 },
  { name: '龙岩市', value: 26 },
  { name: '绍兴市', value: 22 },
  { name: '新余市', value: 47 },
  { name: '和田地区', value: 66 },
  { name: '新乡市', value: 78 },
  { name: '澳门半岛', value: 69 },
  { name: '吴忠市', value: 13 },
  { name: '安康市', value: 16 },
  { name: '铁岭市', value: 65 },
  { name: '达州市', value: 4 },
  { name: '黄石市', value: 59 },
  { name: '海口市', value: 54 },
  { name: '黄山市', value: 57 },
  { name: '松原市', value: 26 },
  { name: '海南藏族自治州', value: 70 },
  { name: '苏州市', value: 92 },
  { name: '四平市', value: 2 },
  { name: '东营市', value: 22 },
  { name: '吴忠市', value: 73 },
  { name: '重庆市', value: 74 },
  { name: '威海市', value: 21 },
  { name: '延安市', value: 8 },
  { name: '鸡西市', value: 16 },
  { name: '安庆市', value: 47 },
  { name: '宁德市', value: 75 },
  { name: '南充市', value: 59 },
  { name: '九龙', value: 43 },
  { name: '天津市', value: 40 },
  { name: '山南地区', value: 74 },
  { name: '商洛市', value: 52 },
  { name: '永州市', value: 35 },
  { name: '黄冈市', value: 13 },
  { name: '宣城市', value: 24 },
  { name: '哈密地区', value: 45 },
  { name: '天津市', value: 71 },
  { name: '天津市', value: 6 },
  { name: '丽江市', value: 21 },
  { name: '山南地区', value: 62 },
  { name: '郑州市', value: 15 },
  { name: '来宾市', value: 68 },
  { name: '成都市', value: 35 },
  { name: '上海市', value: 18 },
  { name: '娄底市', value: 21 },
  { name: '白银市', value: 35 },
  { name: '阜阳市', value: 54 },
  { name: '澳门半岛', value: 46 },
  { name: '运城市', value: 47 },
  { name: '克拉玛依市', value: 29 },
  { name: '滨州市', value: 75 },
  { name: '新乡市', value: 17 },
  { name: '台州市', value: 80 },
  { name: '三亚市', value: 27 },
  { name: '嘉峪关市', value: 37 },
  { name: '葫芦岛市', value: 34 },
  { name: '漯河市', value: 10 },
  { name: '营口市', value: 29 },
  { name: '天津市', value: 95 },
  { name: '齐齐哈尔市', value: 47 },
  { name: '北京市', value: 9 },
  { name: '离岛', value: 5 },
  { name: '惠州市', value: 44 },
  { name: '广安市', value: 69 },
  { name: '天津市', value: 94 },
  { name: '达州市', value: 61 },
  { name: '天津市', value: 43 },
  { name: '吉林市', value: 74 },
  { name: '聊城市', value: 88 },
  { name: '阿勒泰地区', value: 15 },
  { name: '曲靖市', value: 68 },
  { name: '益阳市', value: 69 },
  { name: '衡阳市', value: 15 },
  { name: '日喀则地区', value: 55 },
  { name: '遵义市', value: 81 },
  { name: '太原市', value: 80 },
  { name: '巢湖市', value: 37 },
  { name: '香港岛', value: 68 },
  { name: '来宾市', value: 84 },
  { name: '三亚市', value: 66 },
  { name: '重庆市', value: 97 },
];

const Page: FC = () => <TagCloud data={data} height={343} />;

export default Page;
